version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:26.2.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  cassandra:
    image: cassandra:5.0.4
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 5s
      timeout: 10s
      retries: 30
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster

  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      keycloak:
        condition: service_started
      cassandra:
        condition: service_healthy
    environment:
      - CASSANDRA_HOST=cassandra
      - KEYCLOAK_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo9hsZYzmEOZQukHVPJKEUflDoiyDG7eUjluLb+pwG6Q3Wsmpx4yp6hGa9f7Q4qFFW0IyvOg50VBd3nURDA8ZpmUTWLSOWdhUhJNLDjiw1TGA/9nE8jPrYHdZHywgDYIMeGshLvLPJnjwzyese4jjjZy8lJMwXT1Kvj4fmD3vZAy9imPSwvO99o2qPI9TlSebaBPpuYQVwuNQB8PXO0tpsayylOg94tOYhhXge5ug40LYO7PA1f2vXAbKukVtgNJnwN2nuIZI+2oONb7LN2HqycrFEFJdoRK4YJEq50jydTF2iMxmGmgKpB9+Ss2WBg6bMP6HgG15IU3lr/M1VOkBxQIDAQAB
      - KEYCLOAK_ISSUER=http://keycloak:8080/realms/mon-realm
      - KEYCLOAK_AUDIENCE=react-client

volumes:
  cassandra_data:
  keycloak_data: